version: '3.8'
services:
  postgres:
    container_name: dashboard_db
    image: postgres:14.4
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=dashboard_db
      - TZ=Asia/Jakarta
      - PGTZ=Asia/Jakarta
    # volumes:
    #   - ./db:/db
    ports:
      - 5432:5432
  client:
    container_name: client
    # build:
    #   # context: ./client
    #   dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # restart: always
    # volumes:
    #   - ./configurations:/usr/share/nginx/html/config/
    depends_on:
      - "postgres"
    environment:
      - NODE_ENV=production
      - PORT=8000

# volumes:
#   db: